version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./script/nginx.conf:/etc/nginx/nginx.conf
      - ./script/nginx.server.conf:/etc/nginx/nginx.server.conf
    container_name: front-web
